[versions]
errorprone = "2.49.0"
junit = "6.0.3"
slf4j = "2.0.12"

[libraries]
errorprone_annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone" }
errorprone_core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-reload4j = { module = "org.slf4j:slf4j-log4j12", version.ref = "slf4j" }

[plugins]
errorprone = "net.ltgt.errorprone:5.1.0"
versions = "com.github.ben-manes.versions:0.54.0"

